# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"\xf6\x01\n\tDebugInfo\x12\x0f\n\x07isDebug\x18\x01 \x01(\x08\x12\x18\n\tfixedRole\x18\x02 \x01(\x0e\x32\x05.Role\x12\x19\n\x11\x66ixedRoleClientId\x18\x03 \x01(\t\x12\x12\n\ndaySeconds\x18\x04 \x01(\x05\x12\x16\n\x0e\x65veningSeconds\x18\x05 \x01(\x05\x12\x14\n\x0cnightSeconds\x18\x06 \x01(\x05\x12\x0e\n\x06useLLM\x18\x07 \x01(\x08\x12\x1d\n\x15nonTargetableClientId\x18\x08 \x01(\t\x12\x18\n\x10observerClientId\x18\t \x01(\t\x12\x18\n\x10\x63ontinueOnlyBots\x18\n \x01(\x08\"r\n\x08GameInfo\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x13\n\x0bplayerCount\x18\x02 \x01(\x05\x12\x12\n\nmafiaCount\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x1d\n\tdebugInfo\x18\x05 \x01(\x0b\x32\n.DebugInfo*\\\n\x04Role\x12\x10\n\x0cRole_UNKNOWN\x10\x00\x12\x10\n\x0cRole_CITIZEN\x10\x01\x12\x0e\n\nRole_MAFIA\x10\x02\x12\x0f\n\x0bRole_POLICE\x10\x03\x12\x0f\n\x0bRole_DOCTOR\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=381
  _globals['_ROLE']._serialized_end=473
  _globals['_DEBUGINFO']._serialized_start=17
  _globals['_DEBUGINFO']._serialized_end=263
  _globals['_GAMEINFO']._serialized_start=265
  _globals['_GAMEINFO']._serialized_end=379
# @@protoc_insertion_point(module_scope)
