# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"T\n\tGameStart\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x13\n\x0bplayerCount\x18\x02 \x01(\x05\x12\x12\n\nmafiaCount\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\"!\n\x11GameStartResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTART']._serialized_start=14
  _globals['_GAMESTART']._serialized_end=98
  _globals['_GAMESTARTRESPONSE']._serialized_start=100
  _globals['_GAMESTARTRESPONSE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
