# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipc.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_data_pb2 as game__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tipc.proto\x12\x06ipc_pb\x1a\x0fgame_data.proto\"7\n\x0fGameParticipant\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x14\n\x0cparticipants\x18\x02 \x03(\t\"V\n\x13GameServerConnected\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x31\n\x10gameParticipants\x18\x02 \x03(\x0b\x32\x17.ipc_pb.GameParticipant\"\"\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"i\n\x0cStartNewGame\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x1f\n\x07\x63lients\x18\x02 \x03(\x0b\x32\x0e.ipc_pb.Client\x12(\n\x08gameInfo\x18\x03 \x01(\x0b\x32\x16.game_data_pb.GameInfo\"\x16\n\x14StartNewGameResponse\"0\n\x0c\x43lientExited\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\"\x16\n\x14\x43lientExitedResponse\"\x1b\n\tGameEnded\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"\x13\n\x11GameEndedResponse\"\x0f\n\rRestartServer\"\x11\n\x0fServerRestartedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEPARTICIPANT']._serialized_start=38
  _globals['_GAMEPARTICIPANT']._serialized_end=93
  _globals['_GAMESERVERCONNECTED']._serialized_start=95
  _globals['_GAMESERVERCONNECTED']._serialized_end=181
  _globals['_CLIENT']._serialized_start=183
  _globals['_CLIENT']._serialized_end=217
  _globals['_STARTNEWGAME']._serialized_start=219
  _globals['_STARTNEWGAME']._serialized_end=324
  _globals['_STARTNEWGAMERESPONSE']._serialized_start=326
  _globals['_STARTNEWGAMERESPONSE']._serialized_end=348
  _globals['_CLIENTEXITED']._serialized_start=350
  _globals['_CLIENTEXITED']._serialized_end=398
  _globals['_CLIENTEXITEDRESPONSE']._serialized_start=400
  _globals['_CLIENTEXITEDRESPONSE']._serialized_end=422
  _globals['_GAMEENDED']._serialized_start=424
  _globals['_GAMEENDED']._serialized_end=451
  _globals['_GAMEENDEDRESPONSE']._serialized_start=453
  _globals['_GAMEENDEDRESPONSE']._serialized_end=472
  _globals['_RESTARTSERVER']._serialized_start=474
  _globals['_RESTARTSERVER']._serialized_end=489
  _globals['_SERVERRESTARTED']._serialized_start=491
  _globals['_SERVERRESTARTED']._serialized_end=508
# @@protoc_insertion_point(module_scope)
