# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipc.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tipc.proto\"/\n\x11GameServerStarted\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\"\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"F\n\x0cStartNewGame\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x18\n\x07\x63lients\x18\x03 \x03(\x0b\x32\x07.Client\"$\n\x14StartNewGameResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\t\">\n\x0c\x43lientExited\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\")\n\tGameEnded\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESERVERSTARTED']._serialized_start=13
  _globals['_GAMESERVERSTARTED']._serialized_end=60
  _globals['_CLIENT']._serialized_start=62
  _globals['_CLIENT']._serialized_end=96
  _globals['_STARTNEWGAME']._serialized_start=98
  _globals['_STARTNEWGAME']._serialized_end=168
  _globals['_STARTNEWGAMERESPONSE']._serialized_start=170
  _globals['_STARTNEWGAMERESPONSE']._serialized_end=206
  _globals['_CLIENTEXITED']._serialized_start=208
  _globals['_CLIENTEXITED']._serialized_end=270
  _globals['_GAMEENDED']._serialized_start=272
  _globals['_GAMEENDED']._serialized_end=313
# @@protoc_insertion_point(module_scope)
