# generated by compile_proto.py

from typing import Callable, Type, Any
from mafia_chatbot.network.messages import *

messageTypeDict: dict[Type, int] = {
    error_pb2.RequestError : 0,
    auth_pb2.Auth : 1000,
    auth_pb2.AuthResponse : 1001,
    game_pb2.GameStart : 2000,
    game_pb2.GameStartResponse : 2001,
    game_pb2.RequestGamePhase : 2002,
    game_pb2.GamePhase : 2003,
    game_pb2.RequestGameState : 2004,
    game_pb2.GameState : 2005,
}

def _RequestErrorMessageFactory(data: bytes) -> error_pb2.RequestError :
    message = error_pb2.RequestError()
    message.ParseFromString(data)
    return message

def _AuthMessageFactory(data: bytes) -> auth_pb2.Auth :
    message = auth_pb2.Auth()
    message.ParseFromString(data)
    return message

def _AuthResponseMessageFactory(data: bytes) -> auth_pb2.AuthResponse :
    message = auth_pb2.AuthResponse()
    message.ParseFromString(data)
    return message

def _GameStartMessageFactory(data: bytes) -> game_pb2.GameStart :
    message = game_pb2.GameStart()
    message.ParseFromString(data)
    return message

def _GameStartResponseMessageFactory(data: bytes) -> game_pb2.GameStartResponse :
    message = game_pb2.GameStartResponse()
    message.ParseFromString(data)
    return message

def _RequestGamePhaseMessageFactory(data: bytes) -> game_pb2.RequestGamePhase :
    message = game_pb2.RequestGamePhase()
    message.ParseFromString(data)
    return message

def _GamePhaseMessageFactory(data: bytes) -> game_pb2.GamePhase :
    message = game_pb2.GamePhase()
    message.ParseFromString(data)
    return message

def _RequestGameStateMessageFactory(data: bytes) -> game_pb2.RequestGameState :
    message = game_pb2.RequestGameState()
    message.ParseFromString(data)
    return message

def _GameStateMessageFactory(data: bytes) -> game_pb2.GameState :
    message = game_pb2.GameState()
    message.ParseFromString(data)
    return message


messageFactoryDict: dict[int, Callable[[bytes], Any]] = {
    0 : _RequestErrorMessageFactory,
    1000 : _AuthMessageFactory,
    1001 : _AuthResponseMessageFactory,
    2000 : _GameStartMessageFactory,
    2001 : _GameStartResponseMessageFactory,
    2002 : _RequestGamePhaseMessageFactory,
    2003 : _GamePhaseMessageFactory,
    2004 : _RequestGameStateMessageFactory,
    2005 : _GameStateMessageFactory,
}
