# generated by compile_proto.py

from typing import Callable, Type, Any
from mafia_chatbot.network.messages import *

messageTypeDict: dict[Type, int] = {
    error_pb2.RequestError : 0,
    auth_pb2.Auth : 1000,
    auth_pb2.AuthResponse : 1001,
    game_pb2.RequestMyGameInfo : 2000,
    game_pb2.MyGameInfo : 2001,
    game_pb2.GameStart : 2002,
    game_pb2.GameStartResponse : 2003,
    game_pb2.JoinMyGame : 2004,
    game_pb2.JoinMyGameResponse : 2005,
    game_pb2.RequestGamePhase : 2006,
    game_pb2.GamePhase : 2007,
    game_pb2.RequestGameState : 2008,
    game_pb2.GameState : 2009,
    game_pb2.RequestChatList : 2010,
    game_pb2.ChatList : 2011,
    game_pb2.RequestAddChat : 2012,
    game_pb2.GetChat : 2013,
    game_pb2.AddChat : 2014,
    game_pb2.SetTarget : 2015,
    game_pb2.SetTargetResponse : 2016,
    game_pb2.GetVoteState : 2017,
    game_pb2.VoteState : 2018,
    game_pb2.Removed : 2019,
    game_pb2.GameEnd : 2020,
    game_pb2.QuitGame : 2021,
    game_pb2.QuitGameResponse : 2022,
}

def _RequestErrorMessageFactory(data: bytes) -> error_pb2.RequestError :
    message = error_pb2.RequestError()
    message.ParseFromString(data)
    return message

def _AuthMessageFactory(data: bytes) -> auth_pb2.Auth :
    message = auth_pb2.Auth()
    message.ParseFromString(data)
    return message

def _AuthResponseMessageFactory(data: bytes) -> auth_pb2.AuthResponse :
    message = auth_pb2.AuthResponse()
    message.ParseFromString(data)
    return message

def _RequestMyGameInfoMessageFactory(data: bytes) -> game_pb2.RequestMyGameInfo :
    message = game_pb2.RequestMyGameInfo()
    message.ParseFromString(data)
    return message

def _MyGameInfoMessageFactory(data: bytes) -> game_pb2.MyGameInfo :
    message = game_pb2.MyGameInfo()
    message.ParseFromString(data)
    return message

def _GameStartMessageFactory(data: bytes) -> game_pb2.GameStart :
    message = game_pb2.GameStart()
    message.ParseFromString(data)
    return message

def _GameStartResponseMessageFactory(data: bytes) -> game_pb2.GameStartResponse :
    message = game_pb2.GameStartResponse()
    message.ParseFromString(data)
    return message

def _JoinMyGameMessageFactory(data: bytes) -> game_pb2.JoinMyGame :
    message = game_pb2.JoinMyGame()
    message.ParseFromString(data)
    return message

def _JoinMyGameResponseMessageFactory(data: bytes) -> game_pb2.JoinMyGameResponse :
    message = game_pb2.JoinMyGameResponse()
    message.ParseFromString(data)
    return message

def _RequestGamePhaseMessageFactory(data: bytes) -> game_pb2.RequestGamePhase :
    message = game_pb2.RequestGamePhase()
    message.ParseFromString(data)
    return message

def _GamePhaseMessageFactory(data: bytes) -> game_pb2.GamePhase :
    message = game_pb2.GamePhase()
    message.ParseFromString(data)
    return message

def _RequestGameStateMessageFactory(data: bytes) -> game_pb2.RequestGameState :
    message = game_pb2.RequestGameState()
    message.ParseFromString(data)
    return message

def _GameStateMessageFactory(data: bytes) -> game_pb2.GameState :
    message = game_pb2.GameState()
    message.ParseFromString(data)
    return message

def _RequestChatListMessageFactory(data: bytes) -> game_pb2.RequestChatList :
    message = game_pb2.RequestChatList()
    message.ParseFromString(data)
    return message

def _ChatListMessageFactory(data: bytes) -> game_pb2.ChatList :
    message = game_pb2.ChatList()
    message.ParseFromString(data)
    return message

def _RequestAddChatMessageFactory(data: bytes) -> game_pb2.RequestAddChat :
    message = game_pb2.RequestAddChat()
    message.ParseFromString(data)
    return message

def _GetChatMessageFactory(data: bytes) -> game_pb2.GetChat :
    message = game_pb2.GetChat()
    message.ParseFromString(data)
    return message

def _AddChatMessageFactory(data: bytes) -> game_pb2.AddChat :
    message = game_pb2.AddChat()
    message.ParseFromString(data)
    return message

def _SetTargetMessageFactory(data: bytes) -> game_pb2.SetTarget :
    message = game_pb2.SetTarget()
    message.ParseFromString(data)
    return message

def _SetTargetResponseMessageFactory(data: bytes) -> game_pb2.SetTargetResponse :
    message = game_pb2.SetTargetResponse()
    message.ParseFromString(data)
    return message

def _GetVoteStateMessageFactory(data: bytes) -> game_pb2.GetVoteState :
    message = game_pb2.GetVoteState()
    message.ParseFromString(data)
    return message

def _VoteStateMessageFactory(data: bytes) -> game_pb2.VoteState :
    message = game_pb2.VoteState()
    message.ParseFromString(data)
    return message

def _RemovedMessageFactory(data: bytes) -> game_pb2.Removed :
    message = game_pb2.Removed()
    message.ParseFromString(data)
    return message

def _GameEndMessageFactory(data: bytes) -> game_pb2.GameEnd :
    message = game_pb2.GameEnd()
    message.ParseFromString(data)
    return message

def _QuitGameMessageFactory(data: bytes) -> game_pb2.QuitGame :
    message = game_pb2.QuitGame()
    message.ParseFromString(data)
    return message

def _QuitGameResponseMessageFactory(data: bytes) -> game_pb2.QuitGameResponse :
    message = game_pb2.QuitGameResponse()
    message.ParseFromString(data)
    return message


messageFactoryDict: dict[int, Callable[[bytes], Any]] = {
    0 : _RequestErrorMessageFactory,
    1000 : _AuthMessageFactory,
    1001 : _AuthResponseMessageFactory,
    2000 : _RequestMyGameInfoMessageFactory,
    2001 : _MyGameInfoMessageFactory,
    2002 : _GameStartMessageFactory,
    2003 : _GameStartResponseMessageFactory,
    2004 : _JoinMyGameMessageFactory,
    2005 : _JoinMyGameResponseMessageFactory,
    2006 : _RequestGamePhaseMessageFactory,
    2007 : _GamePhaseMessageFactory,
    2008 : _RequestGameStateMessageFactory,
    2009 : _GameStateMessageFactory,
    2010 : _RequestChatListMessageFactory,
    2011 : _ChatListMessageFactory,
    2012 : _RequestAddChatMessageFactory,
    2013 : _GetChatMessageFactory,
    2014 : _AddChatMessageFactory,
    2015 : _SetTargetMessageFactory,
    2016 : _SetTargetResponseMessageFactory,
    2017 : _GetVoteStateMessageFactory,
    2018 : _VoteStateMessageFactory,
    2019 : _RemovedMessageFactory,
    2020 : _GameEndMessageFactory,
    2021 : _QuitGameMessageFactory,
    2022 : _QuitGameResponseMessageFactory,
}
