# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operation.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foperation.proto\x12\x0coperation_pb\"\"\n\x0eGetServerState\x12\x10\n\x08language\x18\x01 \x01(\t\"O\n\x0bServerState\x12\x11\n\toperating\x18\x01 \x01(\x08\x12\x14\n\x0cstateMessage\x18\x02 \x01(\t\x12\x17\n\x0fmaintainEndTime\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSERVERSTATE']._serialized_start=33
  _globals['_GETSERVERSTATE']._serialized_end=67
  _globals['_SERVERSTATE']._serialized_start=69
  _globals['_SERVERSTATE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
