# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_data_pb2 as game__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x1a\x0fgame_data.proto\"-\n\x0bParticipant\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"|\n\x08RoomInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tmaxHumans\x18\x02 \x01(\x05\x12\"\n\x0cparticipants\x18\x03 \x03(\x0b\x32\x0c.Participant\x12\x0e\n\x06hostId\x18\x04 \x01(\t\x12\x1b\n\x08gameInfo\x18\x05 \x01(\x0b\x32\t.GameInfo\"!\n\x11RequestMyRoomInfo\x12\x0c\n\x04rqid\x18\x01 \x01(\t\"I\n\nMyRoomInfo\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x14\n\x0cisRoomExists\x18\x02 \x01(\x08\x12\x17\n\x04info\x18\x03 \x01(\x0b\x32\t.RoomInfo\"\\\n\nCreateRoom\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x11\n\tmaxHumans\x18\x02 \x01(\x05\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x1b\n\x08gameInfo\x18\x04 \x01(\x0b\x32\t.GameInfo\"?\n\x12\x43reateRoomResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x1b\n\x08roomInfo\x18\x02 \x01(\x0b\x32\t.RoomInfo\"8\n\x08JoinRoom\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"=\n\x10JoinRoomResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x1b\n\x08roomInfo\x18\x02 \x01(\x0b\x32\t.RoomInfo\"\x18\n\x08QuitRoom\x12\x0c\n\x04rqid\x18\x01 \x01(\t\" \n\x10QuitRoomResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\t\"8\n\x0fRoomInfoUpdated\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x17\n\x04info\x18\x02 \x01(\x0b\x32\t.RoomInfo\"\x1d\n\rRoomDestroyed\x12\x0c\n\x04rqid\x18\x01 \x01(\t\"4\n\x07NewGame\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x1b\n\x08gameInfo\x18\x02 \x01(\x0b\x32\t.GameInfo\"-\n\x0fNewGameResponse\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\")\n\x0bGameStarted\x12\x0c\n\x04rqid\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTICIPANT']._serialized_start=31
  _globals['_PARTICIPANT']._serialized_end=76
  _globals['_ROOMINFO']._serialized_start=78
  _globals['_ROOMINFO']._serialized_end=202
  _globals['_REQUESTMYROOMINFO']._serialized_start=204
  _globals['_REQUESTMYROOMINFO']._serialized_end=237
  _globals['_MYROOMINFO']._serialized_start=239
  _globals['_MYROOMINFO']._serialized_end=312
  _globals['_CREATEROOM']._serialized_start=314
  _globals['_CREATEROOM']._serialized_end=406
  _globals['_CREATEROOMRESPONSE']._serialized_start=408
  _globals['_CREATEROOMRESPONSE']._serialized_end=471
  _globals['_JOINROOM']._serialized_start=473
  _globals['_JOINROOM']._serialized_end=529
  _globals['_JOINROOMRESPONSE']._serialized_start=531
  _globals['_JOINROOMRESPONSE']._serialized_end=592
  _globals['_QUITROOM']._serialized_start=594
  _globals['_QUITROOM']._serialized_end=618
  _globals['_QUITROOMRESPONSE']._serialized_start=620
  _globals['_QUITROOMRESPONSE']._serialized_end=652
  _globals['_ROOMINFOUPDATED']._serialized_start=654
  _globals['_ROOMINFOUPDATED']._serialized_end=710
  _globals['_ROOMDESTROYED']._serialized_start=712
  _globals['_ROOMDESTROYED']._serialized_end=741
  _globals['_NEWGAME']._serialized_start=743
  _globals['_NEWGAME']._serialized_end=795
  _globals['_NEWGAMERESPONSE']._serialized_start=797
  _globals['_NEWGAMERESPONSE']._serialized_end=842
  _globals['_GAMESTARTED']._serialized_start=844
  _globals['_GAMESTARTED']._serialized_end=885
# @@protoc_insertion_point(module_scope)
