reasons = [
    "They are the only person here who is not wearing socks.",
    "I saw them looking at their phone suspiciously, as if receiving secret instructions.",
    "They walked in with an aura of mystery that cannot be ignored.",
    "Their coffee cup is empty, meaning they must have been too busy plotting instead of drinking.",
    "They took exactly three seconds to respond, which is statistically the mafia average.",
    "They sat in the same chair as the last known mafia in the previous game.",
    "They blinked twice when I asked if they were innocent. Highly suspicious.",
    "They adjusted their glasses at a crucial moment, clearly signaling to their mafia allies.",
    "They had a sudden urge to tie their shoelaces while being accused.",
    "They laughed at an unrelated joke, but it felt like a mafia laugh.",
    "They wore red today. Everyone knows red is the color of deception.",
    "They wrote something on their notepad and quickly erased it. Planning something?",
    "They yawned suspiciously, as if trying to appear relaxed.",
    "Their chair squeaked exactly at the moment a mafia was mentioned.",
    "They were humming an ominous tune before the game started.",
    "They used the word 'interesting' in a way that sounded too calculated.",
    "Their pencil broke while they were taking notes—obviously a sign of guilt.",
    "They seem too good at this game. Almost as if they have inside knowledge.",
    "They checked their watch as if waiting for a secret signal.",
    "Their name backwards sounds vaguely threatening.",
    "They sighed deeply when no one else did. What are they frustrated about?",
    "They had a pre-planned excuse for being innocent, which is exactly what a guilty person would do.",
    "They switched their sitting posture at a key moment in the discussion.",
    "Their shoes are too clean for someone who's been 'innocently' walking around.",
    "They didn't react when someone else was accused. A true innocent would be engaged.",
    "They high-fived someone earlier. What kind of secret handshake was that?",
    "They bit their lip when someone mentioned mafia strategies.",
    "They smelled like fresh bread. No relation to the game, but I just find it suspicious.",
    "They scratched their nose as soon as accusations started flying.",
    "They placed their hands in their pockets when asked a direct question.",
    "They adjusted their tie when the game began, as if preparing for something.",
    "They have the exact same number of letters in their name as a previous mafia member.",
    "They didn’t bring a drink. Perhaps they were too busy planning their next move?",
    "They made a dramatic entrance. Only someone hiding something would be that flashy.",
    "They sneezed exactly when someone else was accused. A distraction tactic?",
    "They touched their earlobe at a key moment in the conversation.",
    "They hesitated before saying they were innocent. Innocence should be instant!",
    "They wrote something on their hand earlier. A secret mafia note?",
    "They looked up at the ceiling while thinking. A classic sign of deception.",
    "They crossed their arms when no one else did. Clearly defensive behavior.",
    "They brought their own pen. What were they planning to write?",
    "They were seen whispering to themselves before the game started.",
    "They cracked their knuckles at a suspiciously appropriate time.",
    "They always vote third. Why not first or last? Clearly overthinking their actions.",
    "They smell like oranges. Nothing wrong with that, but I don't trust it.",
    "They made eye contact with me and then immediately looked away.",
    "They stretched too dramatically, as if trying to relieve stress.",
    "They have a very neutral expression, as if trying not to reveal their true thoughts.",
    "They scratched their head when someone mentioned the word 'strategy.'",
    "They exhaled loudly when someone else was accused.",
    "They brought an energy drink. Need extra energy for deception?",
    "They folded their arms too quickly after making a statement.",
    "They have a knowing smile that I just don’t trust.",
    "They seemed too amused when someone else was accused.",
    "They licked their lips right after someone defended them.",
    "They rubbed their chin as if plotting something.",
    "They stretched before speaking, as if preparing a long-winded lie.",
    "They had a mysterious glint in their eye when the discussion started.",
    "They shuffled their feet in a way that seemed too rhythmic to be innocent.",
    "They had a sudden coughing fit after someone accused them.",
    "They looked at me like they knew something I didn’t.",
    "They are sitting at the exact same angle as the last known mafia from the previous game.",
    "They took a deep breath before responding. What were they preparing for?",
    "They adjusted their watch band too many times.",
    "They just have that 'mafia' energy about them.",
    "They keep looking at the exit, as if planning an escape.",
    "They touched their chin, which is a classic sign of deep plotting.",
    "They keep tapping their fingers on the table—nervous, perhaps?",
    "They looked up when accused, instead of maintaining eye contact.",
    "They scratched their wrist right after hearing an accusation.",
    "They seem a little too comfortable in this game.",
    "They adjusted their sleeves at a crucial moment.",
    "They whistled on their way into the room—like someone with nothing to lose.",
    "They checked their phone too quickly after a break.",
    "They wore a hat indoors. What are they hiding under there?",
    "They tapped their foot when the topic of mafia strategies came up.",
    "They switched which leg was crossed when someone accused them.",
    "They let out a suspiciously long 'hmm' when thinking.",
    "They smiled right after someone else was accused.",
    "They asked what time it was as soon as the game started. Planning something?",
    "They blinked three times when accused—too much or too little?",
    "They seem oddly enthusiastic about surviving.",
    "They positioned their drink at a strange angle.",
    "They keep glancing at the moderator—looking for confirmation?",
    "They drummed their fingers when asked a question.",
    "They yawned exactly when someone asked a critical question.",
    "They looked over their shoulder before the game started.",
    "They moved their chair back slightly when called out.",
    "They hesitated just a little too long before agreeing with someone.",
    "They touched their forehead when hearing a key accusation.",
    "They let out a dramatic sigh before making their case.",
    "They gave an oddly specific denial.",
    "They took a sip of water before speaking, as if stalling for time.",
    "They looked down at their hands when someone asked if they were mafia.",
    "They keep adjusting their hoodie strings—what are they hiding?",
    "They leaned in just a little too much when someone else was accused.",
    "They tapped their temple as if accessing secret mafia knowledge.",
    "They avoided stepping on cracks in the floor—clearly a sign of meticulous planning.",
    "They wore mismatched socks. A distracted mind is a guilty mind.",
    "They blinked exactly when the lights flickered. Coincidence? I think not.",
]

print(len(reasons))
