syntax = "proto3";

package auth_pb;

message UserInfo {
  string clientId = 1;
  string name = 2;
}

enum AuthMethod {
  AUTH_METHOD_UNKNOWN = 0;
  AUTH_METHOD_TEST = 1;
  AUTH_METHOD_FIREBASE = 2;
}

message Auth {
  AuthMethod method = 1;
  string token = 2;
  string password = 3;
  bool listen = 4;
}

message AuthResponse {
  UserInfo userInfo = 1;
  string requiredVersion = 2;
}

message UpdateUserInfo {
  UserInfo userInfo = 1;
}

message UpdateUserInfoResponse {
  UserInfo userInfo = 1;
}

message DeleteUser { }

message DeleteUserResponse { }

message DuplicatedSignIn { }

message GetAdsInfo { }

message AdsInfo {
  bool enabled = 1;
  bool useTest = 2;
}
