syntax = "proto3";

message UserInfo {
  string clientId = 1;
  string name = 2;
}

enum AuthMethod {
  AUTH_METHOD_UNKNOWN = 0;
  AUTH_METHOD_TEST = 1;
  AUTH_METHOD_FIREBASE = 2;
}

message Auth {
  string rqid = 1;
  AuthMethod method = 2;
  string token = 3;
  string password = 4;
  bool listen = 5;
}

message AuthResponse {
  string rqid = 1;
  UserInfo userInfo = 2;
  string requiredVersion = 3;
}

message UpdateUserInfo {
  string rqid = 1;
  UserInfo userInfo = 2;
}

message UpdateUserInfoResponse {
  string rqid = 1;
  UserInfo userInfo = 2;
}

message DeleteUser {
  string rqid = 1;
}

message DeleteUserResponse {
  string rqid = 1;
}

message DuplicatedSignIn {
  string rqid = 1;
}

message GetAdsInfo {
  string rqid = 1;
}

message AdsInfo {
  string rqid = 1;
  bool enabled = 2;
}
