syntax = "proto3";

import "game_data.proto";

message CheckCurrentGame {
  string rqid = 1;
}

message CurrentGame {
  string rqid = 1;
  bool isGameExists = 2;
  int32 port = 3;
}

message RequestCurrentGameInfo {
  string rqid = 1;
}

message CurrentGameInfo {
  string rqid = 1;
  GameInfo info = 2;
}

message ReadyGame {
  string rqid = 1;
}

message ReadyGameResponse {
  string rqid = 1;
}

message RequestGamePhase {
  string rqid = 1;
}

message GamePhase {
  string rqid = 1;
  int32 round = 2;
  Phase phase = 3;
  float phaseEndTime = 4;
  float phaseRemainTime = 5;
}

message RequestGameState {
  string rqid = 1;
}

message GameState {
  string rqid = 1;

  string language = 2;
  repeated Player players = 3;
  Player me = 4;

  int32 mafiaCount = 5;
  int32 remainMafiaCount = 6;

  GamePhase phase = 7;

  int32 remainMyChat = 8;
  int32 maxMyChat = 9;
}

message RequestChatList {
  string rqid = 1;
}

message ChatList {
  string rqid = 1;
  repeated Chat chats = 2;
}

message RequestAddChat {
  string rqid = 1;
  Chat chat = 2;
}

message GetChat {
  string rqid = 1;
  int32 index = 2;
}

message AddChat {
  string rqid = 1;
  Chat chat = 2;
  int32 remainMyChat = 3;
  int32 maxMyChat = 4;
}

message SetTarget {
  string rqid = 1;
  TargetType type = 2;
  string target = 3;
}

message SetTargetResponse {
  string rqid = 1;
}

message GetVoteState {
  string rqid = 1;
  TargetType type = 2;
}

message VoteState {
  string rqid = 1;
  TargetType type = 2;
  map<string, Voters> votersMap = 3;
}

message Removed {
  string rqid = 1;
  RemoveReason reason = 2;
}

message GameEnd {
  string rqid = 1;
  GameEndReason reason = 2;
}

message QuitGame {
  string rqid = 1;
}

message QuitGameResponse {
  string rqid = 1;
}

message ReportChat {
  string rqid = 1;
  string reporterId = 2;
  int32 chatIndex = 3;
  string comment = 4;
}

message ReportChatResponse {
  string rqid = 1;
}
