syntax = "proto3";

import "google/protobuf/timestamp.proto";

message GameStart {
  string rqid = 1;
  int32 playerCount = 2;
  int32 mafiaCount = 3;
  string language = 4;
}

message GameStartResponse {
  string rqid = 1;
}

enum Role {
  Role_UNKNOWN = 0;
  Role_CITIZEN = 1;
  Role_MAFIA = 2;
  Role_POLICE = 3;
  Role_DOCTOR = 4;
}

message Player {
  string id = 1;
  string name = 2;
  Role role = 3;
  bool isLive = 4;
}

enum Phase {
  Phase_UNKNOWN = 0;
  Phase_DAY = 1;
  Phase_EVENING = 2;
  Phase_NIGHT = 3;
}

message RequestGameState {
  string rqid = 1;
}

message GameState {
  string rqid = 1;

  string language = 2;
  repeated Player players = 3;
  int32 mafiaCount = 4;
  int32 remainMafiaCount = 5;

  string myId = 6;
  string myName = 7;
  Role myRole = 8;

  int32 round = 9;
  Phase phase = 10;
  google.protobuf.Timestamp phaseEndTime = 11;
  int32 phaseRemainTime = 12;
}

message RequestGamePhase {
  string rqid = 1;
}

message GamePhase {
  string rqid = 1;
  int32 round = 2;
  Phase phase = 3;
  google.protobuf.Timestamp phaseEndTime = 4;
  int32 phaseRemainTime = 5;
}
