syntax = "proto3";

import "google/protobuf/timestamp.proto";

message GameStart {
  string rqid = 1;
  int32 playerCount = 2;
  int32 mafiaCount = 3;
  string language = 4;
}

message GameStartResponse {
  string rqid = 1;
}

enum Role {
  Role_UNKNOWN = 0;
  Role_CITIZEN = 1;
  Role_MAFIA = 2;
  Role_POLICE = 3;
  Role_DOCTOR = 4;
}

message Player {
  string id = 1;
  string name = 2;
  Role role = 3;
  bool isLive = 4;
}

enum Phase {
  Phase_UNKNOWN = 0;
  Phase_DAY = 1;
  Phase_EVENING = 2;
  Phase_NIGHT = 3;
}

message RequestGamePhase {
  string rqid = 1;
}

message GamePhase {
  string rqid = 1;
  int32 round = 2;
  Phase phase = 3;
  google.protobuf.Timestamp phaseEndTime = 4;
  int32 phaseRemainTime = 5;
}

message RequestGameState {
  string rqid = 1;
}

message GameState {
  string rqid = 1;

  string language = 2;
  repeated Player players = 3;
  Player me = 4;

  int32 mafiaCount = 5;
  int32 remainMafiaCount = 6;

  GamePhase phase = 7;
}

enum ChatType {
  CHAT_UNKNOWN = 0;
  CHAT_SYSTEM = 1;
  CHAT_DISCUSSION = 2;
}

message Chat {
  string id = 1;
  ChatType type = 2;
  int32 index = 3;

  string sender = 4;
  string content = 5;
}

message RequestChatList {
  string rqid = 1;
}

message ChatList {
  string rqid = 1;
  repeated Chat chats = 2;
}

message RequestAddChat {
  string rqid = 1;
  Chat chat = 2;
}

message GetChat {
  string rqid = 1;
  int32 index = 2;
}

message AddChat {
  string rqid = 1;
  Chat chat = 2;
  int32 remainMyChat = 3;
  int32 maxMyChat = 4;
}

enum TargetType {
  TARGET_UNKNOWN = 0;
  TARGET_VOTE = 1;
  TARGET_KILL = 2;
  TARGET_TEST = 3;
  TARGET_HEAL = 4;
}

message SetTarget {
  string rqid = 1;
  TargetType type = 2;
  string target = 3;
}

message SetTargetResponse {
  string rqid = 1;
}

message GetVoteState {
  string rqid = 1;
}

message Voters {
  repeated string voters = 1;
}

message VoteState {
  string rqid = 1;
  map<string, Voters> votersMap = 2;
}
