syntax = "proto3";

package ipc_pb;

import "game_data.proto";

message GameParticipant {
  string gameId = 1;
  repeated string participants = 2;
}

message GameServerConnected {
  int32 port = 1;
  repeated GameParticipant gameParticipants = 2;
}

message Client {
  string id = 1;
  string name = 2;
}

message StartNewGame {
  string gameId = 1;
  repeated Client clients = 2;
  game_data_pb.GameInfo gameInfo = 3;
}

message StartNewGameResponse { }

message ClientExited {
  string gameId = 1;
  string clientId = 2;
}

message ClientExitedResponse { }

message GameEnded {
  string gameId = 1;
}

message GameEndedResponse { }

message RestartServer { }

message ServerRestarted { }
