syntax = "proto3";

import "game_data.proto";

message GameParticipant {
  string gameId = 1;
  repeated string participants = 2;
}

message GameServerConnected {
  string rqid = 1;
  int32 port = 2;
  repeated GameParticipant gameParticipants = 3;
}

message Client {
  string id = 1;
  string name = 2;
}

message StartNewGame {
  string rqid = 1;
  string gameId = 2;
  repeated Client clients = 3;
  GameInfo gameInfo = 4;
}

message StartNewGameResponse {
  string rqid = 1;
}

message ClientExited {
  string rqid = 1;
  string gameId = 2;
  string clientId = 3;
}

message ClientExitedResponse {
  string rqid = 1;
}

message GameEnded {
  string rqid = 1;
  string gameId = 2;
}

message GameEndedResponse {
  string rqid = 1;
}
