syntax = "proto3";

message GameServerStarted {
  string rqid = 1;
  int32 port = 2;
}

message Client {
  string id = 1;
  string name = 2;
}

message StartNewGame {
  string rqid = 1;
  string gameId = 2;
  repeated Client clients = 3;
}

message StartNewGameResponse {
  string rqid = 1;
}

message ClientExited {
  string rqid = 1;
  string gameId = 2;
  string clientId = 3;
}

message ClientExitedResponse {
  string rqid = 1;
}

message GameEnded {
  string rqid = 1;
  string gameId = 2;
}

message GameEndedResponse {
  string rqid = 1;
}
