syntax = "proto3";

package room_pb;

import "game_data.proto";

message Participant {
  string clientId = 1;
  string name = 2;
}

message RoomInfo {
  string code = 1;
  int32 maxHumans = 2;
  repeated Participant participants = 3;
  string hostId = 4;
  game_data_pb.GameInfo gameInfo = 5;
}

message RequestMyRoomInfo { }

message MyRoomInfo {
  bool isRoomExists = 1;
  RoomInfo info = 2;
}

message CreateRoom {
  int32 maxHumans = 1;
  string password = 2;
  game_data_pb.GameInfo gameInfo = 3;
}

message CreateRoomResponse {
  RoomInfo roomInfo = 1;
}

message JoinRoom {
  string code = 1;
  string password = 2;
}

message JoinRoomResponse {
  RoomInfo roomInfo = 1;
}

message QuitRoom { }

message QuitRoomResponse { }

message RoomInfoUpdated {
  RoomInfo info = 1;
}

message RoomDestroyed { }

message NewGame {
  game_data_pb.GameInfo gameInfo = 1;
}

message NewGameResponse {
  int32 port = 1;
}

message GameStarted {
  int32 port = 1;
}
